/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]

use ffi::size_t;
use procps::message_fn;

extern "C" {
    pub static mut xalloc_err_handler: message_fn;
}
extern "C" {
    pub fn xcalloc(size: ::std::os::raw::c_uint) -> *mut ::std::os::raw::c_void;
    pub fn xmalloc(size: size_t) -> *mut ::std::os::raw::c_void;
    pub fn xrealloc(oldp: *mut ::std::os::raw::c_void, size: ::std::os::raw::c_uint) -> *mut ::std::os::raw::c_void;
    pub fn xstrdup(str: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
