/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub type message_fn =
    ::std::option::Option<unsafe extern "C" fn(arg1: *const ::std::os::raw::c_char, ...)>;
