/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]

use ffi::{gid_t, uid_t};
extern "C" {
    pub fn pwcache_get_user(uid: uid_t) -> *mut ::std::os::raw::c_char;
    pub fn pwcache_get_group(gid: gid_t) -> *mut ::std::os::raw::c_char;
}

pub static P_G_SZ: ::std::os::raw::c_int = 33;
