/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub fn lookup_wchan(pid: ::std::os::raw::c_int)
     -> *const ::std::os::raw::c_char;
}
