/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub fn print_uptime(human_readable: ::std::os::raw::c_int);
    pub fn sprint_uptime(human_readable: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char;
}
